# Generated by Django 4.1.7 on 2024-05-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_student_parents_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='classes', to='base.subject'),
        ),
    ]
