# Generated by Django 4.1.7 on 2024-04-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_class_options_alter_items_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='disability_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passport',
            field=models.ImageField(null=True, upload_to='passport'),
        ),
    ]
