# Generated by Django 4.1.7 on 2024-05-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_teacher_cv_alter_teacher_flsc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cv',
            field=models.FileField(null=True, upload_to="cv's"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='flsc',
            field=models.FileField(null=True, upload_to='teacher_documents'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='other_certificate',
            field=models.FileField(null=True, upload_to='other_certificate'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='secondary_school_transcript',
            field=models.FileField(null=True, upload_to='teacher_documents'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='university_polytech_institution_cer',
            field=models.FileField(null=True, upload_to='teacher_documents'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='university_polytech_institution_cer_trans',
            field=models.FileField(null=True, upload_to='teacher_documents'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='waec_neco_nabteb_gce',
            field=models.FileField(null=True, upload_to='teacher_documents'),
        ),
    ]
