# Generated by Django 4.1.7 on 2024-04-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_student_disability_note_student_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='computer_skills',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cv',
            field=models.ImageField(null=True, upload_to="cv's"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='disability_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='flsc',
            field=models.ImageField(null=True, upload_to='teacher_documents'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='maritial_status',
            field=models.CharField(blank=True, choices=[('married', 'MARRIED'), ('single', 'SINGLE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='other_certificate',
            field=models.ImageField(null=True, upload_to='other_certificate'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='passport',
            field=models.ImageField(null=True, upload_to='teachers_passport'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='permanent_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='secondary_school_transcript',
            field=models.ImageField(null=True, upload_to='teacher_documents'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_speech',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='temporary_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='university_polytech_institution_cer',
            field=models.ImageField(null=True, upload_to='teacher_documents'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='university_polytech_institution_cer_trans',
            field=models.ImageField(null=True, upload_to='teacher_documents'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='waec_neco_nabteb_gce',
            field=models.ImageField(null=True, upload_to='teacher_documents'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.ImageField(null=True, upload_to='student_passport'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='disability',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='religion',
            field=models.CharField(blank=True, choices=[('christian', 'CHRISTIAN'), ('muslim', 'MUSLIM'), ('others', 'OTHERS')], max_length=30, null=True),
        ),
    ]
