# Generated by Django 4.1.7 on 2024-04-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_schoolphotos_alter_event_image_alter_items_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(choices=[('Learning Development Class', 'Learning Development Class'), ('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Nursery 3', 'Nursery 3'), ('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6'), ('Primary 7', 'Primary 7'), ('Primary 8', 'Primary 8'), ('Primary 9', 'Primary 9')], max_length=50),
        ),
    ]
