# Generated by Django 4.1.7 on 2024-04-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_class_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolphotos',
            options={'verbose_name_plural': 'School Photos'},
        ),
    ]
