# Generated by Django 5.0.6 on 2024-05-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_result_agility_result_attentiveness_result_caring_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parents',
            options={'verbose_name_plural': 'Parents'},
        ),
    ]
