# Generated by Django 4.1.7 on 2024-04-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_term_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(blank=True, choices=[('first term', 'FIRST TERM'), ('second term', 'SECOND TERM'), ('third term', 'THIRD TERM')], max_length=50, null=True),
        ),
    ]
