# Generated by Django 5.0.6 on 2024-05-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_parents_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='subject',
        ),
        migrations.AddField(
            model_name='scheme',
            name='subject',
            field=models.ManyToManyField(related_name='scheme_subjects', to='base.subject'),
        ),
    ]
