# Generated by Django 4.1.7 on 2024-04-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_term_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='exam',
            field=models.FloatField(blank=True, null=True, verbose_name='EXAM (60%)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='TOTAL (100%)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_ca',
            field=models.FloatField(blank=True, null=True, verbose_name='Total C.A. Score (40%)'),
        ),
    ]
