# Generated by Django 5.0.6 on 2024-05-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_scheme_subject_scheme_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='subject',
        ),
        migrations.AddField(
            model_name='scheme',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subject'),
        ),
    ]
