# Generated by Django 5.0.6 on 2024-05-27 14:56

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_scheme_subject_scheme_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='scheme',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='scheme'),
        ),
    ]
