# Generated by Django 5.0.6 on 2024-06-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_bill_payment_session_payment_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='children_name',
        ),
        migrations.AddField(
            model_name='parents',
            name='children_name',
            field=models.TextField(null=True),
        ),
    ]
