# Generated by Django 5.0.6 on 2024-06-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_parents_children_name_parents_children_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill',
            new_name='Bills',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='children_name',
        ),
        migrations.AlterField(
            model_name='payment',
            name='fee_type',
            field=models.CharField(choices=[('School Fees', 'School Fees'), ('P.T.A Bills', 'Pta Bills'), ('Other Bills', 'Other Bills')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parents',
            name='children_name',
            field=models.ManyToManyField(related_name='Students', to='base.student'),
        ),
    ]
