# Generated by Django 5.0.6 on 2024-06-23 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_rename_bill_bills_remove_parents_children_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bills'),
        ),
    ]
