# Generated by Django 5.0.6 on 2024-06-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_payment_fee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='children_name',
        ),
        migrations.AddField(
            model_name='parents',
            name='children_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
