from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(User)
admin.site.register(StudentProfile)
admin.site.register(Student)
admin.site.register(Teacher)
admin.site.register(Parents)
admin.site.register(Subject)
admin.site.register(Class)
admin.site.register(Items)
admin.site.register(Event)
admin.site.register(Notification)
admin.site.register(SchoolPhotos)
admin.site.register(Term)
admin.site.register(Session)
admin.site.register(Scheme)
admin.site.register(Result)
admin.site.register(SubjectResult)
admin.site.register(Email)
admin.site.register(ScratchCard)
admin.site.register(Cart)
admin.site.register(CartItem)
admin.site.register(Payment)
admin.site.register(Bills)
admin.site.register(StudentPassword)
